# Generated by Django 3.2.3 on 2021-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210517_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=128)),
                ('col2', models.CharField(max_length=128)),
                ('col3', models.CharField(max_length=128)),
                ('col4', models.CharField(max_length=128)),
                ('col5', models.CharField(max_length=128)),
            ],
        ),
    ]
