# Generated by Django 3.2.3 on 2021-05-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyInfo',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrowserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.policyinfo')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.siteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPolicy',
            fields=[
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.clientinfo')),
                ('client_usb', models.BooleanField(default=False)),
                ('client_browser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.policyinfo')),
            ],
        ),
    ]
