# Generated by Django 3.2.3 on 2021-06-24 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpolicy',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientpolicy',
            name='client_browser',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BrowserPolicy',
        ),
        migrations.DeleteModel(
            name='ClientInfo',
        ),
        migrations.DeleteModel(
            name='ClientPolicy',
        ),
        migrations.DeleteModel(
            name='PolicyInfo',
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
